spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todo_list?useUnicode=yes&characterEncoding=utf8&&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect